import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';


import {
  MatToolbarModule,
  MatSortModule,
  MatButtonModule,
  MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  MatSnackBarModule,
  MatDialogModule,
  MatIconModule,
  MatSliderModule,
  MatTabsModule,
  MatSlideToggleModule,
  MatSidenavModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatListModule,
  MatMenuModule,
  MatRadioModule,
  MatTooltipModule,
  MatProgressSpinnerModule,
  MatProgressBarModule,
  MatGridListModule,
  MatSelectModule,
  MatStepperModule,
  MatChipsModule,
  MatAutocompleteModule,
  MatPaginatorModule,
  MatInputModule,
  MatDatepickerModule,
  MatTableModule
} from '@angular/material';
import { InputFile } from './inputFile';


@NgModule({
  imports: [
    CommonModule,
    MatToolbarModule,
    MatSortModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatSnackBarModule,
    MatDialogModule,
    MatIconModule,
    MatSliderModule,
    MatTabsModule,
    MatSlideToggleModule,
    MatSidenavModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatListModule,
    MatMenuModule,
    MatRadioModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatGridListModule,
    MatSelectModule,
    MatStepperModule,
    MatChipsModule,
    MatAutocompleteModule,
    MatPaginatorModule,
    MatInputModule,
    MatDatepickerModule,
    MatTableModule
  ],
  exports: [
    MatToolbarModule,
    MatSortModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatSnackBarModule,
    MatDialogModule,
    MatIconModule,
    MatSliderModule,
    MatTabsModule,
    MatSlideToggleModule,
    MatSidenavModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatListModule,
    MatMenuModule,
    MatRadioModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatGridListModule,
    MatSelectModule,
    MatStepperModule,
    MatChipsModule,
    MatAutocompleteModule,
    MatPaginatorModule,
    MatInputModule,
    MatDatepickerModule,
    MatTableModule,
    InputFile
  ],
  declarations: [
    InputFile
  ]
})
export class MaterialModule { }
